### ISSUE TITLE
Include an example where we specify Ready condition, in status,to be false

### ISSUE THREAD

**Issue by Avni-Sharma** [servicebinding/website#13]
We have provided examples and documentation https://github.com/k8s-service-bindings/spec/blob/master/README.md#reconciler-implementation for the `True` status of `Ready` type condition. While it might seem obvious as to when the readiness fails/is false, i.e in the absence of service, but maybe we can be explicit about it in the doc and example.
For example:
```
status:
  conditions:
  - type:   Ready
    status: 'False'
```
